<?php 

/*
define('TWEET_LIMIT', 5);
define('TWITTER_USERNAME', 'YOUR_TWITTER');
define('CONSUMER_KEY', 'YOUR_KEY');
define('CONSUMER_SECRET', 'YOUR_SECRET_KEY');
define('ACCESS_TOKEN', 'YOUR_TOKEN');
define('ACCESS_TOKEN_SECRET', 'YOUR_TOKEN_SECRET') ;
*/


define('TWEET_LIMIT', 5);
define('TWITTER_USERNAME', 'YOUR_TWITTER');
define('CONSUMER_KEY', 'bA6NAfDcZZmXV0S07Rg');
define('CONSUMER_SECRET', 'g6Nh7TjPcIeKWl4GYVgSjGXbzPAGMf2tuXV9ixBHI');
define('ACCESS_TOKEN', '17892212-yM3hlGmM6svGn9XmBe8G8awYwtpWIFRp91809BwB8');
define('ACCESS_TOKEN_SECRET', 'CaXgHkX3TW5qTCB61eHSH9uGKUqUHruaBhZbWVU6jdwfC') ;


?>
